### ISSUE TITLE
添加工具一直loading 无发添加

### ISSUE THREAD

**Issue by crendy** [Mereithhh/van-nav-extension#4]
添加工具一直loading 无发添加

**Comment by dingdangdog** [comment]
如果做了反代，建议检查服务状态，正常是没问题的
![image](https://github.com/Mereithhh/van-nav-extension/assets/45959431/64ec51f7-5fe9-4536-a219-a3a6c6c6583e)

**Comment by nageshuizeii** [comment]
![CleanShot 2025-01-06 at 00 19 59@2x](https://github.com/user-attachments/assets/2d6bdc30-ee66-40d6-9949-ed6ad83f69e4)
同上，/api/admin/tool option报错404，其他get均报200完成

**Comment by 495462724** [comment]
from origin 'chrome-extension://jaelkjmlbafjnmldgdcmjcpodopgcphg' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
服务端要支持跨域啊

**Comment by nageshuizeii** [comment]
您好，请问有具体解决方式吗

**Comment by 495462724** [comment]
当您在开发或使用 Microsoft Edge 扩展时遇到跨域问题，通常是因为浏览器的安全机制——同源策略（Same-Origin Policy）限制了从一个源加载的文档或脚本与来自其他源的资源之间的交互。对于非简单请求，浏览器会在实际请求之前发送预检请求（preflight request），即 OPTIONS 请求，以询问服务器是否允许即将发生的实际请求。如果服务器没有正确配置 CORS（Cross-Origin Resource Sharing）响应头，则会导致跨域请求失败
1
。
解决方案
1. 服务器端配置 CORS
最理想的解决方案是在服务器端添加适当的 CORS 响应头。确保服务器返回的响应包含以下头部信息：
Access-Control-Allow-Origin: 指定哪些源可以访问资源，可以用星号表示任何源，但在涉及凭据的情况下，必须指定确切的源。
Access-Control-Allow-Methods: 如果是非简单请求，需要列出允许的方法。
Access-Control-Allow-Headers: 对于包含额外 HTTP 头部的请求，这里应该列出所有被允许的自定义头部。
Access-Control-Allow-Credentials: 如果需要发送凭据（如 Cookies），则设置为 true。
通过这种方式，您可以确保服务器能够接受来自 Edge 扩展程序的跨域请求，并且这些请求可以在生产环境中稳定工作
2
。
2. 修改扩展权限声明
在 Edge 扩展中，您还可以通过修改 manifest.json 文件中的 permissions 字段来声明所需的权限，从而确保扩展程序能够正确地进行跨域请求。例如：
Json深色版本
{ "name": "MyExtension", "version": "1.0", "manifest_version": 3, "permissions": [ "http://192.168.6.2:6412/", // 或者更广泛的匹配模式 "webRequest", "webRequestBlocking" ], ... }
这样做的好处是让您的扩展明确告知浏览器它需要访问哪些特定的 URL 模式，从而获得必要的权限来执行跨域请求
7
。
3. 使用 no-cors 模式
如果您不需要透明的响应数据，即不关心响应的具体内容，而只是想触发某个操作，那么可以将 fetch 请求的 mode 设置为 'no-cors'。不过需要注意的是，这样做会导致响应成为不透明的（opaque），意味着你只能知道请求成功与否，但无法读取响应的具体内容。这种方式适用于那些不需要读取响应内容的情况，比如上传文件等。
Javascript深色版本
fetch('http://192.168.6.2:6412/api/admin/all', { method: 'GET', mode: 'no-cors' });
但是，在大多数情况下，这种方法并不是最优解，因为它限制了开发者对响应数据的访问
2
。
4. 开发调试期间临时禁用安全检查
在开发阶段，为了方便调试，您可以选择暂时关闭浏览器的安全功能，如同源策略。请注意，这仅适用于本地开发环境，并不适合用于生产部署。可以通过创建一个新的 Edge 快捷方式并在目标路径后附加参数 --disable-web-security --user-data-dir=C:\edgeDevData 来实现这一点。这种方式会启动一个新的 Edge 实例，其中的安全特性被禁用，从而允许跨域请求
18
。
然而，考虑到安全性的重要性，建议尽可能避免这种方法，尤其是在处理敏感数据时。相反，应该优先考虑调整服务器端的 CORS 设置或者优化客户端代码以符合 CORS 规范。
5. 使用浏览器插件解决跨域问题
另外，也可以安装专门设计用来解决跨域问题的浏览器插件，如 moesif CORS extension。这类插件可以在不修改服务器配置的情况下帮助开发者绕过 CORS 限制，非常适合用于快速测试和开发场景
19
。
综上所述，面对 Edge 扩展中的跨域问题，最佳实践是首先尝试从服务器端着手解决问题，确保 API 服务正确设置了 CORS 响应头。其次，根据实际情况调整扩展的 manifest 文件，赋予其必要的权限。最后，在开发过程中，可以选择合适的工具和技术手段来简化调试流程，但始终要保持对安全性的关注。
可以试试，我加了 mode: 'no-cors' 这个，检查发现有效，但是分类有时候还是老失败
495462724
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2025年1月9日 ***@***.***>***@***.***>,
***@***.***>主题Re: [Mereithhh/van-nav-extension] 添加工具一直loading 无发添加 (Issue #4)
您好，请问有具体解决方式吗

**Comment by nageshuizeii** [comment]
![CleanShot 2025-01-09 at 01 13 13@2x](https://github.com/user-attachments/assets/d513967f-2778-4500-91df-344cb09d5e92)
我咨询了ChatGPT，用了相关插件，发现还是不能正常使用

**Comment by nageshuizeii** [comment]
可以试试，我加了 mode: 'no-cors' 这个，检查发现有效，但是分类有时候还是老失败

请问mode怎么添加哇🥲

**Comment by 495462724** [comment]
解决了，这里是https，改成http就好了，就很快了
495462724
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2025年1月9日 ***@***.***>***@***.***>,
***@***.***>主题Re: [Mereithhh/van-nav-extension] 添加工具一直loading 无发添加 (Issue #4)
可以试试，我加了 mode: 'no-cors' 这个，检查发现有效，但是分类有时候还是老失败
请问mode怎么添加哇🥲

**Comment by nageshuizeii** [comment]
具体指的是修改哪里呢

Thanks


495462724 ***@***.***>于2025年1月9日 周四01:22写道：

**Comment by 495462724** [comment]
495462724
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2025年1月9日 ***@***.***>***@***.***>,
***@***.***>主题Re: [Mereithhh/van-nav-extension] 添加工具一直loading 无发添加 (Issue #4)
具体指的是修改哪里呢 
Thanks 
495462724 ***@***.***>于2025年1月9日 周四01:22写道：

**Comment by nageshuizeii** [comment]
没有看到需要改哪里

**Comment by openapphub** [comment]
服务端增加允许跨域是最简单合理的，看作者什么时候合并了，或者有更好的方案。我本地先构建了一个使用着了

**Comment by openapphub** [comment]
时好时坏，离谱~
```
popup.html:1 Access to fetch at 'http://localhost:6412/api/admin/tool' from origin 'chrome-extension://cibppfnpngndmlddefipdjldejjadkjk' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
14:59:31.398 action.js:253  POST http://localhost:6412/api/admin/tool net::ERR_FAILED
postData @ action.js:253
fetchAddTool @ action.js:248
handleConfirm @ action.js:160
14:59:31.398 action.js:253   Uncaught (in promise) TypeError: Failed to fetch
    at postData (action.js:253:26)
    at fetchAddTool (action.js:248:16)
    at HTMLButtonElement.handleConfirm (action.js:160:21)
```

**Comment by openapphub** [comment]
> 时好时坏，离谱~
> 
> ```
> popup.html:1 Access to fetch at 'http://localhost:6412/api/admin/tool' from origin 'chrome-extension://cibppfnpngndmlddefipdjldejjadkjk' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 14:59:31.398 action.js:253  POST http://localhost:6412/api/admin/tool net::ERR_FAILED
> postData @ action.js:253
> fetchAddTool @ action.js:248
> handleConfirm @ action.js:160
> 14:59:31.398 action.js:253   Uncaught (in promise) TypeError: Failed to fetch
>     at postData (action.js:253:26)
>     at fetchAddTool (action.js:248:16)
>     at HTMLButtonElement.handleConfirm (action.js:160:21)
> ```

实测还是调整下服务端代码允许跨域才可以。

**Comment by nageshuizeii** [comment]
我自己是改成 https 就好了

**Comment by openapphub** [comment]
> 我自己是改成 https 就好了

我部署了两套，一本本地用 brew 安装和管理。一套是公网HTTPS。我是本地使用有问题，时好时坏，最后改了下作者服务端端代码构建了下就好了。
